[web]
10.0.0.5 ansible_user=ubuntu

[monitoring]
10.0.0.136 ansible_user=ubuntu

[all:vars]
ansible_ssh_private_key_file=~/.ssh/devops-bootcamp
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
